### ISSUE TITLE
How to replace WriteFormulaNum

### ISSUE THREAD

**Issue by o3o** [symmetryinvestments/xlsxd#49]
My app use your (great)  xlsxd 1.2.3:
```
...
dependency "xlsxd" version="~>1.2.3"
```

I want upgrade to 3.1.6
```
dependency "xlsxd" version="~>3.1.6"
```

but:

```
no property writeFormulaNum for type Worksheet
```

I have tried with `writeFormulaNumImpl` but does't work..

So, which is the function that replaces `writeFormulaNum`?

Thank you very much

**Comment by burner** [comment]
@o3o should be good now, I also added a test to verify.
Thanks for taking the time to report this.

**Comment by o3o** [comment]
You're welcome. Thank you for writing this useful library
