### ISSUE TITLE
Add libxlsxwriter topic to the project metadata

### ISSUE THREAD

**Issue by jmcnamara** [symmetryinvestments/xlsxd#51]
Hi,

Could you add libxlsxwriter as a "topic" metadata to your project so that users can find wrappers in different languages.

Topic/Metadata are shown at the top of the project: https://github.com/jmcnamara/libxlsxwriter

Other examples: https://github.com/search?q=topic%3Alibxlsxwriter&type=Repositories

Thanks,

John

**Comment by burner** [comment]
done

thank you for the hint

**Comment by jmcnamara** [comment]
Thank you for adding this and for what looks like very good support for libsxwriter from D.

**Comment by burner** [comment]
the cool part about D is that calling C is trivial, C and D are ABI compatible.
Better yet, the D community has a tool called DPP that takes C header and writes a D file with all the function and struct declarations.
All I did then was to use a hand full of vim macros to build a OO D shim over the C OO interface.
